AUTOMAKE_OPTIONS = foreign

AM_FFLAGS = -ffixed-line-length-none -cpp -I$(srcdir)/../qt -I$(srcdir)/../hpoly

noinst_LTLIBRARIES = libqt.la
libqt_la_SOURCES = IntFuncqT.f qT_req_fun.f myLi4.f

libqt_la_SOURCES += CONVOS/tgagaga/P1qqP1qqP1qqD2.f	   \
	            CONVOS/tgagaga/P1ggP1ggP1ggD0.f        \
	            CONVOS/tgagaga/P1ggP1ggP1ggD1.f	   \
	            CONVOS/tgagaga/P1ggP1ggP1ggD2.f	   \
	            CONVOS/tgagaga/P1ggP1ggP1ggdelta.f     \
	            CONVOS/tgagaga/P1ggP1ggP1ggreg.f       \
	            CONVOS/tgagaga/P1ggP1ggP1gq.f	   \
	            CONVOS/tgagaga/P1ggP1gqP1qg.f	   \
	            CONVOS/tgagaga/P1ggP1gqP1qq.f	   \
	            CONVOS/tgagaga/P1gqP1qgP1gq.f	   \
	            CONVOS/tgagaga/P1gqP1qqP1qg.f	   \
	            CONVOS/tgagaga/P1gqP1qqP1qq.f	   \
	            CONVOS/tgagaga/P1qgP1ggP1gg.f	   \
	            CONVOS/tgagaga/P1qgP1ggP1gq.f	   \
	            CONVOS/tgagaga/P1qgP1gqP1qg.f	   \
	            CONVOS/tgagaga/P1qqP1qgP1gg.f	   \
	            CONVOS/tgagaga/P1qqP1qqP1qg.f	   \
	            CONVOS/tgagaga/P1qqP1qqP1qqD0.f	   \
	            CONVOS/tgagaga/P1qqP1qqP1qqD1.f	   \
	            CONVOS/tgagaga/P1qqP1qqP1qqdelta.f     \
	            CONVOS/tgagaga/P1qqP1qqP1qqreg.f


libqt_la_SOURCES += CONVOS/tcgaga/C1gqP1qgP1gg.f  \
	            CONVOS/tcgaga/C1gqP1qgP1gq.f  \
	            CONVOS/tcgaga/C1gqP1qqP1qg.f  \
	            CONVOS/tcgaga/C1gqP1qqP1qq.f  \
	            CONVOS/tcgaga/C1qgP1ggP1gg.f  \
	            CONVOS/tcgaga/C1qgP1ggP1gq.f  \
	            CONVOS/tcgaga/C1qgP1gqP1qg.f  \
	            CONVOS/tcgaga/C1qgP1gqP1qq.f  \
	            CONVOS/tcgaga/C1qqP1qgP1gg.f  \
	            CONVOS/tcgaga/C1qqP1qgP1gq.f  \
	            CONVOS/tcgaga/C1qqP1qqP1qg.f  \
                    CONVOS/tcgaga/C1qqP1qqP1qq.f

libqt_la_SOURCES += CONVOS/tc2ga1/C2ggP1ggD0.f       \
                    CONVOS/tc2ga1/C2ggP1ggD1.f	     \
                    CONVOS/tc2ga1/C2ggP1ggdelta.f    \
                    CONVOS/tc2ga1/C2ggP1gg.f	     \
                    CONVOS/tc2ga1/C2ggP1ggreg.f	     \
                    CONVOS/tc2ga1/C2gqPqg.f	     \
                    CONVOS/tc2ga1/C2gqPqq.f	     \
                    CONVOS/tc2ga1/Cgg2Pgq1.f	     \
                    CONVOS/tc2ga1/P1ggC2qg.f	     \
                    CONVOS/tc2ga1/P1gqC2qg.f	     \
                    CONVOS/tc2ga1/P1qgC2qqb.f	     \
                    CONVOS/tc2ga1/P1qgC2qq.f	     \
                    CONVOS/tc2ga1/P1qgC2qqp.f	     \
                    CONVOS/tc2ga1/P1qqC2qqb.f	     \
                    CONVOS/tc2ga1/P1qqC2qqHSD0.f     \
                    CONVOS/tc2ga1/P1qqC2qqHSD1.f     \
                    CONVOS/tc2ga1/P1qqC2qqHSdelta.f  \
                    CONVOS/tc2ga1/P1qqC2qqHSreg.f    \
                    CONVOS/tc2ga1/P1qqC2qqp.f


libqt_la_SOURCES += CONVOS/tc1ga2/C1gqP2qg.f   \
                    CONVOS/tc1ga2/C1gqP2qq.f   \
                    CONVOS/tc1ga2/C1qgP2gg.f   \
                    CONVOS/tc1ga2/C1qgP2gq.f   \
                    CONVOS/tc1ga2/C1qqP2qg.f   \
                    CONVOS/tc1ga2/C1qqP2qqbV.f \
                    CONVOS/tc1ga2/C1qqP2qqS.f  \
                    CONVOS/tc1ga2/C1qqP2qqV.f

libqt_la_SOURCES += CONVOS/tga1ga2/P1ggP2ggD1.f     \
                    CONVOS/tga1ga2/P1ggP2ggreg.f    \
                    CONVOS/tga1ga2/P1ggP2qg.f	    \
                    CONVOS/tga1ga2/P1gqP2gg.f	    \
                    CONVOS/tga1ga2/P1gqP2qg.f	    \
                    CONVOS/tga1ga2/P1qgP2gg.f	    \
                    CONVOS/tga1ga2/P1qgP2gq.f	    \
                    CONVOS/tga1ga2/P1qgP2qq.f	    \
                    CONVOS/tga1ga2/P1qqP2gq.f	    \
                    CONVOS/tga1ga2/P1qqP2qg.f	    \
                    CONVOS/tga1ga2/P1qqP2qqbV.f	    \
                    CONVOS/tga1ga2/P1qqP2qqS.f	    \
                    CONVOS/tga1ga2/P1qqP2qqVD0.f    \
                    CONVOS/tga1ga2/P1qqP2qqVD1.f    \
                    CONVOS/tga1ga2/P1qqP2qqVdelta.f \
                    CONVOS/tga1ga2/P1qqP2qqVreg.f   \
                    CONVOS/tga1ga2/P2gqP1gg.f	    \
                    CONVOS/tga1ga2/P2qgP1gq.f	    \
                    CONVOS/tga1ga2/P2qqP1gq.f	    \
                    CONVOS/tga1ga2/Pgg1Pgg2D0.f	    \
                    CONVOS/tga1ga2/Pgg1Pgg2delta.f 

libqt_la_SOURCES += tgamma3/P3NSminusD0.f        \
                    tgamma3/P3NSminusdelta.f	 \
                    tgamma3/P3NSminusReg.f	 \
                    tgamma3/P3NSplusD0.f	 \
                    tgamma3/P3NSplusdelta.f	 \
                    tgamma3/P3NSplusReg.f	 \
                    tgamma3/P3NSs.f		 \
                    tgamma3/P3ps.f		 \
                    tgamma3/P3qg.f		 \
                    tgamma3/P3qqbV.f		 \
                    tgamma3/P3qqVD0.f		 \
                    tgamma3/P3qqVdelta.f	 \
                    tgamma3/P3qqV.f		 \
                    tgamma3/P3Sqqb.f		 \
                    tgamma3/P3Sqq.f		 \
                    tgamma3/Pgg3D0en1.f		 \
                    tgamma3/Pgg3D0.f		 \
                    tgamma3/Pgg3delta.f		 \
                    tgamma3/Pgg3.f		 \
                    tgamma3/Pgq3.f		 
                    #tgamma3/xpij2e.f		 \
                    #tgamma3/xpij2p.f		 
                    #tgamma3/xpns2e.f             \
                    #tgamma3/xpns2p.f


pkginclude_HEADERS = qt_interface.h qt_constants.f nf.f types.f qTsubtCoeffs.f
